
-- Public read access for production tables
drop policy if exists "Public read institutions" on institutions;
create policy "Public read institutions" on institutions for select using (true);
drop policy if exists "Public read faculties" on faculties;
create policy "Public read faculties" on faculties for select using (true);
drop policy if exists "Public read departments" on departments;
create policy "Public read departments" on departments for select using (true);
drop policy if exists "Public read courses" on courses;
create policy "Public read courses" on courses for select using (true);
drop policy if exists "Public read course_aliases" on course_aliases;
create policy "Public read course_aliases" on course_aliases for select using (true);
drop policy if exists "Public read subjects" on subjects;
create policy "Public read subjects" on subjects for select using (true);
drop policy if exists "Public read subject_aliases" on subject_aliases;
create policy "Public read subject_aliases" on subject_aliases for select using (true);
drop policy if exists "Public read admission_requirements" on admission_requirements;
create policy "Public read admission_requirements" on admission_requirements for select using (true);
drop policy if exists "Public read olevel_requirements" on olevel_requirements;
create policy "Public read olevel_requirements" on olevel_requirements for select using (true);
drop policy if exists "Public read utme_requirements" on utme_requirements;
create policy "Public read utme_requirements" on utme_requirements for select using (true);
drop policy if exists "Public read direct_entry" on direct_entry;
create policy "Public read direct_entry" on direct_entry for select using (true);
drop policy if exists "Public read post_utme" on post_utme;
create policy "Public read post_utme" on post_utme for select using (true);
drop policy if exists "Public read aggregate_formulas" on aggregate_formulas;
create policy "Public read aggregate_formulas" on aggregate_formulas for select using (true);
drop policy if exists "Public read departmental_cutoffs" on departmental_cutoffs;
create policy "Public read departmental_cutoffs" on departmental_cutoffs for select using (true);
drop policy if exists "Public read catchment" on catchment;
create policy "Public read catchment" on catchment for select using (true);
drop policy if exists "Public read elds" on elds;
create policy "Public read elds" on elds for select using (true);
drop policy if exists "Public read fees" on fees;
create policy "Public read fees" on fees for select using (true);
drop policy if exists "Public read deadlines" on deadlines;
create policy "Public read deadlines" on deadlines for select using (true);
drop policy if exists "Public read admission_news" on admission_news;
create policy "Public read admission_news" on admission_news for select using (true);
drop policy if exists "Public read source_documents" on source_documents;
create policy "Public read source_documents" on source_documents for select using (true);
drop policy if exists "Public read crawl_logs" on crawl_logs;
create policy "Public read crawl_logs" on crawl_logs for select using (true);
drop policy if exists "Public read knowledge_versions" on knowledge_versions;
create policy "Public read knowledge_versions" on knowledge_versions for select using (true);