
-- Service role has full access (for crawler)
drop policy if exists "Service role full access institutions" on institutions;
create policy "Service role full access institutions" on institutions for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access faculties" on faculties;
create policy "Service role full access faculties" on faculties for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access departments" on departments;
create policy "Service role full access departments" on departments for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access courses" on courses;
create policy "Service role full access courses" on courses for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access course_aliases" on course_aliases;
create policy "Service role full access course_aliases" on course_aliases for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access subjects" on subjects;
create policy "Service role full access subjects" on subjects for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access subject_aliases" on subject_aliases;
create policy "Service role full access subject_aliases" on subject_aliases for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access admission_requirements" on admission_requirements;
create policy "Service role full access admission_requirements" on admission_requirements for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access olevel_requirements" on olevel_requirements;
create policy "Service role full access olevel_requirements" on olevel_requirements for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access utme_requirements" on utme_requirements;
create policy "Service role full access utme_requirements" on utme_requirements for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access direct_entry" on direct_entry;
create policy "Service role full access direct_entry" on direct_entry for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access post_utme" on post_utme;
create policy "Service role full access post_utme" on post_utme for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access aggregate_formulas" on aggregate_formulas;
create policy "Service role full access aggregate_formulas" on aggregate_formulas for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access departmental_cutoffs" on departmental_cutoffs;
create policy "Service role full access departmental_cutoffs" on departmental_cutoffs for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access catchment" on catchment;
create policy "Service role full access catchment" on catchment for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access elds" on elds;
create policy "Service role full access elds" on elds for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access fees" on fees;
create policy "Service role full access fees" on fees for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access deadlines" on deadlines;
create policy "Service role full access deadlines" on deadlines for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access admission_news" on admission_news;
create policy "Service role full access admission_news" on admission_news for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access source_documents" on source_documents;
create policy "Service role full access source_documents" on source_documents for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access crawl_logs" on crawl_logs;
create policy "Service role full access crawl_logs" on crawl_logs for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access knowledge_versions" on knowledge_versions;
create policy "Service role full access knowledge_versions" on knowledge_versions for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access raw_crawl_data" on raw_crawl_data;
create policy "Service role full access raw_crawl_data" on raw_crawl_data for all using (auth.role() = 'service_role');
drop policy if exists "Service role full access validated_data" on validated_data;
create policy "Service role full access validated_data" on validated_data for all using (auth.role() = 'service_role');